# -*- coding: utf-8 -*-
"""data-analysis-capstone-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYcVcgVjbxSK8vTO18p8oL7yGu_wxUR3

# DATA ANALYSIS CAPESTONE

## Importing Libraries (Toolkit)
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



"""## Importing & Inspecting Data"""

startups = pd.read_excel('datasets/startup-expansion.xlsx')
startups

startups.info()

startups[['Marketing Spend','Revenue']].describe().round(2)



"""## Preprocessing Data"""

startups['City'].nunique()

startups['City'].unique()

startups['City'].value_counts()

startups['State'].unique()

startups['State'].nunique()

startups['State'].value_counts()

startups['Sales Region'].unique()

startups['Sales Region'].value_counts()

startups['New Expansion'].unique()

startups['New Expansion'].value_counts()

startups.isna().sum()

startups.duplicated().sum()

len(startups['Store ID'].value_counts())



"""## Exploring & Analysing Data"""

startups.sample(10)

startups['Sales Region'].value_counts().plot.bar()

startups.groupby('New Expansion')

startups[startups['New Expansion'] == 'Old'].groupby(['State']).sum()['Revenue'].nlargest(10)

startups[startups['New Expansion'] == 'New'].groupby(['State']).sum()['Revenue'].nlargest(10)

# round((startups['Revenue'] / startups['Marketing Spend']) * 100,2)

startups['Profit'] = startups['Revenue'] - startups['Marketing Spend']

startups

startups['ROMS'] = round((startups['Profit'] / startups['Marketing Spend']) * 100, 2)

startups['ROMS%'] = startups['ROMS'] / 100

startups

startups.to_csv('startups-expansion-modified.csv')



"""==========

# GOOD LUCK!
"""